### ISSUE TITLE
CRAN submission?

### ISSUE THREAD

**Issue by sckott** [fmichonneau/rotl#14]
Any plans for a CRAN submission?  I'm hoping to move phylomatic fxns out of `taxize` into https://github.com/ropensci/branching, which also wraps this pkg. 

thanks! :smile:  -s

**Comment by fmichonneau** [comment]
yes! I'm hoping to polish the last bits during the idigbio hackathon and
submit soon after.

On Wed, May 27, 2015 at 7:47 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
okay, thanks, feel free to close

**Comment by dwinter** [comment]
@fmichonneau feel free to designate any tasks that need doing:

I don't have lots of time for this but am happy to make some effort to get this up to a release.

**Comment by fmichonneau** [comment]
OK, @dwinter I'll let you know! The hackathon is next week Wed-Fri.
