### ISSUE TITLE
Option for chatty return?

### ISSUE THREAD

**Issue by bbanbury** [fmichonneau/rotl#2]
I would love to see an option in function calls for chatty returns (ie, print statements to screen) that give some sort of update.  I am currently downloading a tree of about 400 taxa and it has been going for over 30 minutes.  Not sure if it is dead or chugging along...

**Comment by fmichonneau** [comment]
Currently, a tree with ~14,000 taxa takes ~10 sec. So I don't think we need this anymore. Feel free to re-open if you think it's really needed.
