### ISSUE TITLE
put code initial vignette into repo

### ISSUE THREAD

**Issue by fmichonneau** [fmichonneau/rotl#23]
@dwinter it would be great to have your blue fish red fish vignette in the repo.

I'm running out of time today to do it and don't want to forget, but feel free to push it if you have time.

**Comment by dwinter** [comment]
Will try and get this done today @fmichonneau, shall I add it to the existing vignette (under a new heading)?

Might take a little while as the example in the original one doesn't seem to work anymore...

**Comment by fmichonneau** [comment]
I was initially thinking of having it as a separate vignette, but I think it would be fine as new heading in the existing one.

Don't spend too much time on it if it doesn't work anymore. It would just be nice to have something that shows how to include the results from OTL with data from other public sources.

 Thanks!

**Comment by dwinter** [comment]
OK, I'll see if I can cook up a new example, because it looks like the problem with the old one is one the OpenTree side opentreeoflife/oti#41

**Comment by fmichonneau** [comment]
New vignette is now merged.
