### ISSUE TITLE
Inproperly formatted study trees?

### ISSUE THREAD

**Issue by dwinter** [fmichonneau/rotl#33]
Not sure whether to report this to the RNCL repo, OpenTree or to this one. But here goes...

At the moment we can't read quite a few of the trees from the studies endpoints. Here's an example:

```r
get_study_tree(study_id="pg_1762", tree_id="tree3549")
```
```
storing implied block: TAXA
storing read block: TREES
Error in build_raw_phylo(ncl) : 
  missing edge lengths are not allowed in phylo class
```

`ape::read.tree` will try and read these files, but the resulting tree is a mess. Half of the edge-lengths are missing and I think some internal nodes are being treated as tips(?)

```r
tf <- tempfile()
get_study_tree("pg_1762", get_tree_ids(meta)[2], file_format="newick", file=tf)
ape::read.tree(tf)
sum(is.na(tr$edge.length))/length(tr$edge.length)
```

```
0.48717
```

And replacing the single quotes and spaces doesn't seem to help
```r
tf2 <- tempfile()
clean <- gsub(" ", "_", gsub("'","",scan(tf,"character", sep="\n")))
cat(clean, file=tf2)
rncl::read_newick_phylo(tf2)
```
```
storing implied block: TAXA
storing read block: TREES
Error in build_raw_phylo(ncl) : 
  missing edge lengths are not allowed in phylo class
```

It seems like this is problem with the conversion to newick format on the Open Tree end, but thought I should check with the devleoper of `rncl` first @fmichonneau !

**Comment by fmichonneau** [comment]
I suspect that Open Tree just provides the trees as they were published. My brain is currently foggy but I'm not sure why you would publish a tree with only some edge lengths. It's technically correct but ape cannot deal with missing edge lengths.

Anyway, I pushed to rncl a quick fix. If the tree to be read misses some branch lengths they are all removed (with a warning) so the tree can be read in. I'm not sure it's the best solution. The other option I can think of, would be to replace these missing edge lengths by an arbitrary number but it seems also far from ideal.
