### ISSUE TITLE
more bad newick strings

### ISSUE THREAD

**Issue by bbanbury** [fmichonneau/rotl#6]
Not sure if this is an issue that can/should be solved by the OT API team or if rotl can solve internally. The OT API returns newick strings in various formats, so that R doesn't seem to know how to read them all in.  I was playing around with the example on the main rotl page, and it works for the first tree in the list, but it can't read trees further down.  I expect that a user may want to examine the different study trees in a given set (maybe to maximize taxonomy for example).  Something like this where you can iterate over the returned trees: 

allTreeData <- NULL
for(i in sequence(length(furry_ids))){
  furry_metadata <- httr::content(get_study_meta(furry_ids[[i]]))
  lista <- unlist(furry_metadata$nexml$treesById)
  lista <- lista[grep("ElementOrder", names(lista))]
  for(j in sequence(length(unlist(lista)))){
    tr_string <- get_study_tree(study=furry_ids[[i]], tree=unlist(lista)[[j]],format="newick")
    tr_string <- gsub(" ", "_", tr_string)  #issues with spaces
    tr_string <- gsub("'", "", tr_string) #issues with apostrophes
    tr <- try(read.tree(text=tr_string))
    allTreeData <- rbind(allTreeData, c(furry_ids[[i]], lista[j], length(tr$tip.label)))
  }
}

Ultimately, it would be good if there were some standards so that multiple trees could be compared.

**Comment by fmichonneau** [comment]
all the trees returned by the furry studies can be imported in R now that rotl relies on rncl to parse the newick strings. I'm closing this for now.
