### ISSUE TITLE
Classes for returns fo various APIs

### ISSUE THREAD

**Issue by dwinter** [fmichonneau/rotl#8]
As we discussed, it would be very helpful to have distinct classes for the lists returned by various functions, especially as many of them are nested lists which will take up many screen on an R session is printed. Let's use this issue as a thread to talk about types of returns we get, and the best methods for them (`print`, `summary`...).

**Comment by fmichonneau** [comment]
I have implemented a few methods to facilitate retrieving of information from some of the taxonomy and gol end points. I'm now working on the studies end point. Closing this for now. If someone feels there should be other methods, please open other issues.

**Comment by dwinter** [comment]
Looks good to me @fmichonneau .... I feel bad about how quickly you setting up these targets and knocking them down. Wish I had time to help out!

**Comment by fmichonneau** [comment]
no worries!
